version: '3.9'
services:
  app:
    container_name: ria-ws
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=ria-postgres
    ports: 
      - "8000:8000"
    networks:
      - backend

volumes:
  pg_data: {}
networks:
  backend: {}